# True: If a item is repaired with its crafting material the enchantments
# don't get lost.
# False: ... enchantments are removed. (Doesn't affect the repair of an 
# redstone sword)
keepEnchantmentsOnRepair: false

# How long should mobs burn when hit with a torch (in seconds)
torchFireTime: 1

sword:
  # You can set any Material for the redstone sword, e.g. 'STICK' will work
  # and will be indestructable. /rs destroy however will destroy it and give
  # you the stored experience back.
  material: IRON_SWORD

  # when the sword consumes a redstone ore how much should be added to the sword?
  redstoneOreAmount: 5

  # How much of the stored xp should be gave back to the player when the sword
  # breaks? 0 = nothing, 1 = 100%, 2 = 50%, 4 = 25%, ...
  reclaimExpFactor: 2

  cost:
    # needed amount of redstone for boost
    boost: 5
    
    # needed amount of enderpearls for teleport
    teleport: 1
    
    # when should the sword get stronger? 5 = always after 5 level
    exp: 5

  multiplier:
    # strengh of speed buff
    boost: 10

  duration:
    # duration of speed buff
    boost: 1

scroll:
  levitation:
    duration: 10
    speed: 0.04
  jump:
    duration: 10
  growth:
    range: 4
  waterwalk:
    duration: 120
  respiration:
    duration: 120
  shield:
    duration: 30
  nightvision:
    duration: 120
  attack:
    duration: 15
    bonus: 5
  poison:
    duration: 30
  reflection:
    duration: 30
    
# Damage dealt by a thrown Axe in half hearts
thrownAxeDamage:
  wood: 7
  stone: 8
  iron: 9
  gold: 7
  diamond: 10
