# You can set any Material for the redstone sword, e.g. 'STICK' will work
# and will be indestructable. /rs destroy however will destroy it and give
# you the stored experience back.

# The amount of (stored) redstone to consum in case to activate the 
# right-click ability. (Speed Boost)

# How much of the stored xp should be gave back to the player when the sword
# breaks? 0 = nothing, 1 = 100%, 2 = 50%, 4 = 25%, ...


sword:
  material: WOOD_SWORD
  redstonOreAmount: 5
  reclaimExpFactor: 2
  cost:
    boost: 5
    teleport: 1
    exp: 20
  multiplier:
    boost: 10
  duration:
    boost: 1



# True: If a item is repaired with its crafting material the enchantments
# don't get lost.
# False: ... enchantments are removed. (Doesn't affect the repair of an 
# redstone sword)
keepEnchantmentsOnRepair: false

# The radius in which a scroll of growth will take effect
scroll:
  growthRadius: 4
  flightTime: 10
  jumpTime: 10
  respirationTime: 120
  
# Damage dealt by a thrown Axe
thrownAxeDamage:
  wood: 7
  stone: 8
  iron: 9
  gold: 7
  diamond: 10
