name: RedstoneSwords
main: io.github.notze.redstoneswords.RedstoneSwords
version: 0.5

commands:
  rstest:
    description: does something i want to test
    usage: Usage /rstest
    permission: 
    permission-message: 
  rshelp:
    description: Display help
    usage: Usage /rshelp
    permission: redstoneSwords.rshelp
    permission-message: You don't have permission <redstoneSwords.rshelp>
  rs:
    description: Redstone Sword commands
    usage: Usage /rs destroy
    permission: redstoneSwords.rs
    permission-message: You don't have permission <redstoneSwords.rs>
  rsclearinventory:
    description: Clears the Inventory
    usage: Usage /rsclearinventory
    permission: redstoneSwords.rsclearinventory
    permission-message: You don't have permission <redstoneSwords.rsclearinventory>
  rsstoreinventory:
    description: Stores the Inventory in a Chest
    usage: Usage /rsstoreinventory
    permission: redstoneSwords.rsstoreinventory
    permission-message: You don't have permission <redstoneSwords.rsstoreinventory>
  rsadmininventory:
    description: Opens an inventory containing all items from this mod
    usage: Usage /rsadmininventory
    permission: redstoneSwords.admin
    permission-message: You don't have permission <cheat.redstoneSwords>